_target_: src.evaluation.speaker.cosine_distance.CosineDistanceEvaluator

# whether to center embeddings before calculating cosine score
center_before_scoring: False

# whether to length-normalize embeddings before calculating cosine score
length_norm_before_scoring: False

# maximum number of samples to use to fit mean/std parameters
# when `use_centering` is True
max_num_training_samples: 0